apiVersion: v1
kind: Service
metadata:
  name: orderer0
  labels:
    app: orderer0
spec:
  type: ClusterIP
  ports:
    - port: 7050
      protocol: TCP
  selector:
    app: orderer0
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: orderer0-deployment
  labels:
    app: orderer0
spec:
  template:
    metadata:
      labels:
        app: orderer0
    spec:
      containers:
      - image: anthonyamanse/kubecon-orderer-peer:latest
        imagePullPolicy: Always
        workingDir: /orderer
        command: ["orderer"]
        name: orderer0
        ports:
        - containerPort: 7050
          name: orderer0
        env:
          - name: ORDERER_GENERAL_LOGLEVEL
            value: "debug"
          - name: ORDERER_GENERAL_LISTENADDRESS
            value: "0.0.0.0"
          - name: ORDERER_GENERAL_GENESISMETHOD
            value: "file"
          - name: ORDERER_GENERAL_GENESISFILE
            value: "/orderer/crypto/genesis.block"
          - name: ORDERER_GENERAL_LOCALMSPID
            value: "OrdererMSP"
          - name: ORDERER_GENERAL_LOCALMSPDIR
            value: "/orderer/crypto/msp"
          - name: ORDERER_GENERAL_TLS_ENABLED
            value: "false"
          # - name: ORDERER_GENERAL_TLS_PRIVATEKEY
          #   value: "/orderer/crypto/tls/server.key"
          # - name: ORDERER_GENERAL_TLS_CERTIFICATE
          #   value: "/orderer/crypto/tls/server.crt"
          # - name: ORDERER_GENERAL_TLS_ROOTCAS
          #   value: "[/orderer/crypto/tls/ca.crt]"
        volumeMounts:
          - name: orderer0-storage
            mountPath: /var/hyperledger/production
            subPath: orderer0
      volumes:
        - name: orderer0-storage
          persistentVolumeClaim:
            claimName: peer-claim
